#!/usr/bin/env python3
"""Independent reference vectors for the LF-IN-RECORD verify regression tests.

This script is NOT the program under test and does not execute roottrace.  It
covers the case the batch-file format cannot express: a target record whose
OWN bytes contain LF.  `roottrace verify` (and the library entry point
`roottrace::verify_membership`) take the record as raw bytes with no LF
splitting, so an external system can legitimately commit to a record that
starts with LF, contains consecutive LFs, and ends with LF.  Such a record
can never appear inside a root/prove batch file (LF is the separator there),
so the proof and trusted root for it are fixed here, independently, from the
record SEQUENCE alone.

Two fixed target records:

  * LF_RICH - starts with LF, contains a run of consecutive LFs, ends with
              LF, and also carries CR, NUL and non-UTF-8 bytes; 100 bytes
              long, so the leaf input 0x00 || record (101 bytes) crosses the
              SHA-256 64-byte block boundary.  Every LF is content: the
              consecutive LFs do NOT mean empty records, and the trailing LF
              is NOT a terminator to strip.
  * ONE_LF  - exactly one LF byte.  It is neither the zero-byte empty record
              (SHA-256(0x00)) nor the empty record a batch file of one LF
              represents; its leaf hash is SHA-256(0x00 || 0x0a).

Both records are committed in two tree shapes:

  * a single-record tree (tree_size 1, empty audit path);
  * LF_BATCH, a 9-record (non-power-of-two, RFC 6962 k=8 split) sequence with
    LF_RICH at position 4 and ONE_LF at position 8 (the lone right subtree).

Roots and audit paths are computed with the two structurally different,
already cross-validated reference algorithms from rfc6962_vectors.py (the
RFC's recursive definition and an order-sensitive stack fold over the
standard library `hashlib.sha256`); they must agree, and the recursive
inclusion verifier must re-hash every proof back to the batch root.  The
mutation vectors used by the Rust tests (trailing LF removed, one internal
LF changed, a single line of the record, the empty record against the
ONE_LF positions) are independently confirmed NOT to recompute the root.

Run:  python3 tests/reference/rfc6962_lf_record_vectors.py
The printed constants are copied verbatim into
tests/verify_lf_record_regression.rs.  Nothing here reads roottrace output,
so the expected values are fixed independently of the implementation being
checked.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rfc6962_vectors import (
    audit_path_fold,
    audit_path_recursive,
    mth_fold,
    mth_recursive,
    rust_byte_string,
    sha256,
    verify_inclusion,
)


def lf_rich_record() -> bytes:
    """The fixed LF-rich target record, built deterministically (no
    randomness): a leading LF, NUL/non-UTF-8/CR bytes, a run of consecutive
    LFs, more CR, a deterministic ASCII fill that pushes the length across
    the SHA-256 64-byte block boundary, and a trailing LF."""
    rec = b"\n"                     # leading LF is content
    rec += b"\x00\xff\xfe\r"        # NUL, non-UTF-8 bytes and CR
    rec += b"lf-rich-record:"
    rec += b"\n\n\n"                # consecutive LFs are content, not empty records
    rec += b"segment-B\r"           # CR inside the record
    rec += b"\n"
    alphabet = b"abcdefghijklmnopqrstuvwxyz0123456789"
    i = 0
    while len(rec) < 99:
        rec += bytes([alphabet[i % len(alphabet)]])
        i += 1
    rec += b"\n"                    # trailing LF is content, not a terminator
    return rec


LF_RICH = lf_rich_record()
ONE_LF = b"\n"

# Structural requirements the Rust tests rely on.
assert len(LF_RICH) == 100
assert 1 + len(LF_RICH) > 64, "leaf input must cross the 64-byte block boundary"
assert LF_RICH[0] == 0x0A and LF_RICH[-1] == 0x0A
assert b"\n\n\n" in LF_RICH
assert 0x00 in LF_RICH and 0x0D in LF_RICH and any(b >= 0x80 for b in LF_RICH)

# The one-LF record is a different record from the empty record.
assert sha256(b"\x00" + ONE_LF) != sha256(b"\x00")

# 9 records (non-power-of-two; RFC 6962 splits k=8): LF_RICH sits inside the
# left subtree at position 4, ONE_LF is the lone right subtree at position 8.
LF_BATCH = [
    b"alpha",            # 0
    b"beta",             # 1
    b"",                 # 2 empty record
    b"gamma\r",          # 3 trailing CR is content
    LF_RICH,             # 4 target: the LF-rich record
    b"\xff\x00z",        # 5 non-UTF-8 and NUL bytes
    b"epsilon",          # 6
    b"zeta\x01tail",     # 7
    ONE_LF,              # 8 target: the record that is exactly one LF
]
assert len(LF_BATCH) == 9


def main():
    print("# Generated by tests/reference/rfc6962_lf_record_vectors.py")
    print("# Two independent RFC 6962 implementations agree for every vector;")
    print("# every proof re-hashes back to its root via the recursive verifier.")
    print()

    # Roots of the two single-record trees (empty audit paths).
    root_lf_rich_single = mth_recursive([LF_RICH])
    root_one_lf_single = mth_recursive([ONE_LF])
    assert root_lf_rich_single == mth_fold([LF_RICH])
    assert root_one_lf_single == mth_fold([ONE_LF])
    assert root_lf_rich_single == sha256(b"\x00" + LF_RICH)
    assert root_one_lf_single == sha256(b"\x00" + ONE_LF)

    # Root of the 9-record batch, both algorithms.
    root_batch = mth_recursive(LF_BATCH)
    assert root_batch == mth_fold(LF_BATCH)

    # Audit paths for the two target positions, both producers, and the
    # recursive verifier must recompute the batch root from each.
    path_m4 = audit_path_recursive(LF_BATCH, 4)
    path_m8 = audit_path_recursive(LF_BATCH, 8)
    assert path_m4 == audit_path_fold(LF_BATCH, 4)
    assert path_m8 == audit_path_fold(LF_BATCH, 8)
    assert verify_inclusion(LF_RICH, 4, 9, path_m4) == root_batch
    assert verify_inclusion(ONE_LF, 8, 9, path_m8) == root_batch
    # Position 8 is the lone right subtree of the k=8 split: one hash, the
    # MTH of the first eight records.
    assert path_m8 == [mth_recursive(LF_BATCH[:8])]

    # The single-record proofs verify too (empty paths).
    assert verify_inclusion(LF_RICH, 0, 1, []) == root_lf_rich_single
    assert verify_inclusion(ONE_LF, 0, 1, []) == root_one_lf_single

    # Mutation vectors the Rust tests use must independently NOT recompute
    # the roots (all are well-formed inputs that simply do not match).
    assert verify_inclusion(LF_RICH[:-1], 4, 9, path_m4) != root_batch  # trailing LF removed
    internal_lf_changed = LF_RICH[:21] + b"\x0b" + LF_RICH[22:]
    assert LF_RICH[21] == 0x0A and len(internal_lf_changed) == len(LF_RICH)
    assert verify_inclusion(internal_lf_changed, 4, 9, path_m4) != root_batch
    assert verify_inclusion(LF_RICH[:-1], 0, 1, []) != root_lf_rich_single
    assert verify_inclusion(internal_lf_changed, 0, 1, []) != root_lf_rich_single
    # No single LINE of the LF-rich record is the record.
    for line in LF_RICH.split(b"\n"):
        assert verify_inclusion(line, 4, 9, path_m4) != root_batch
        assert verify_inclusion(line, 0, 1, []) != root_lf_rich_single
    # The empty record is not the one-LF record, in either tree shape.
    assert verify_inclusion(b"", 8, 9, path_m8) != root_batch
    assert verify_inclusion(b"", 0, 1, []) != root_one_lf_single
    # And the one-LF record is not the empty record of the ONE_LF batch tree
    # from rfc6962_vectors.py (SHA-256(0x00)).
    assert root_one_lf_single != sha256(b"\x00")

    print("# LF_RICH: 100-byte record; starts with LF, consecutive LFs inside,")
    print("# ends with LF, carries CR/NUL/non-UTF-8 bytes; leaf input 101 bytes")
    print("# crosses the SHA-256 64-byte block boundary.")
    print(f"const REC_LF_RICH: &[u8] = {rust_byte_string(LF_RICH)};")
    print()
    print("# ONE_LF: the record that is exactly one LF byte.")
    print("const REC_ONE_LF: &[u8] = b\"\\n\";")
    print()
    print("# Single-record trees (tree_size 1, leaf_index 0, empty audit path):")
    print(f"const ROOT_LF_RICH_SINGLE: &str = \"{root_lf_rich_single.hex()}\";")
    print(f"const ROOT_ONE_LF_SINGLE: &str = \"{root_one_lf_single.hex()}\";")
    print()
    print("# LF_BATCH: 9-record (non-power-of-two) sequence with LF_RICH at")
    print("# position 4 and ONE_LF at position 8 (lone right subtree).")
    print(f"const ROOT_LF_BATCH: &str = \"{root_batch.hex()}\";")
    elems = ", ".join(f'"{h.hex()}"' for h in path_m4)
    print(f"const PATH_LF_BATCH_M4: &[&str] = &[{elems}];")
    elems = ", ".join(f'"{h.hex()}"' for h in path_m8)
    print(f"const PATH_LF_BATCH_M8: &[&str] = &[{elems}];")


if __name__ == "__main__":
    main()
