//! End-to-end regression tests for `roottrace inspect <proof-file>`.
//!
//! `inspect` shows the batch size, record position and root value a proof
//! CLAIMS, without any target record or trusted values. The proof file is
//! judged by the same full proof format as `verify` — including the
//! never-displayed `audit_path` — but no membership check is performed and
//! the output must never claim one.
//!
//! Coverage:
//!   * success: stdout is exactly one JSON line holding only tree_size,
//!     leaf_index and root (integers, 64 lowercase hex), exit 0, stderr empty
//!   * field reordering, JSON whitespace and equivalent \uXXXX escapes do not
//!     change the displayed information
//!   * a well-formed proof whose audit_path could never verify (wrong count,
//!     order or content) still displays: inspect verifies nothing
//!   * corruption anywhere in the proof — including inside audit_path — is a
//!     format error: exit 1, empty stdout, stderr says "invalid proof"
//!   * duplicate fields (also via escapes), tree_size 0 and an out-of-range
//!     leaf_index stay rejected
//!   * tree sizes and indices keep their full 64-bit unsigned meaning
//!   * read failures (missing file, directory) exit 1 with empty stdout;
//!     missing/extra arguments exit 2 with the usage text
//!   * proof paths that are not valid UTF-8 are opened by their raw bytes

mod common;

use std::process::Command;

use common::{TempDir, TempFile};

// The same independently produced constants used by verify_regression.rs
// (generated by tests/reference/rfc6962_vectors.py), never derived from
// roottrace output.
const PAYLOAD_B9: &[u8] =
    b"alpha\nbeta\n\ngamma\nalpha\ndelta\r\n\xff\xfe\x00binary\nepsilon\nzeta\x01tail\n";
const ROOT_B9: &str = "a8a3e76ecf28b850e84cb5465729921212ffd07de3c0e6e170cd233bf723adc3";
const PATH_B9_M4: &[&str] = &[
    "4957faa551907820ed93a476704ffd826ea5502881876c87f3acefc0a8d29bce",
    "b739bc437ae5d551d144d1478ee16d1119ba15b2198a3a8b7c47976c36cb6639",
    "6f2bd73a7406c5089558c115aaae63a717e4c6947c44898e7d9600023ff15d10",
    "5cc496b84d9250622d5de1219d1f156e7973503fbd80f7f3364800bbfa2947d2",
];

fn proof_json(size: u64, index: u64, root: &str, path: &[&str]) -> String {
    let mut out =
        format!("{{\"tree_size\":{size},\"leaf_index\":{index},\"root\":\"{root}\",\"audit_path\":[");
    for (i, h) in path.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        out.push('"');
        out.push_str(h);
        out.push('"');
    }
    out.push_str("]}");
    out
}

fn run(proof_path: &std::path::Path) -> std::process::Output {
    Command::new(common::bin())
        .arg("inspect")
        .arg(proof_path)
        .output()
        .expect("failed to execute roottrace binary")
}

/// The exact one-line summary `inspect` must print for the B9 position-4
/// proof: only the three claimed fields, integers and lowercase hex, one LF.
const EXPECTED_B9_M4_LINE: &str =
    "{\"tree_size\":9,\"leaf_index\":4,\"root\":\"a8a3e76ecf28b850e84cb5465729921212ffd07de3c0e6e170cd233bf723adc3\"}\n";

fn assert_inspect_ok(desc: &str, proof: &[u8], expected_stdout: &str) {
    let prf = TempFile::create(proof);
    let out = run(&prf.path);
    if out.status.code() != Some(0)
        || out.stdout != expected_stdout.as_bytes()
        || !out.stderr.is_empty()
    {
        panic!(
            "[{desc}] expected exit 0, stdout {expected_stdout:?}, empty stderr\n\
             status: {:?}\nstdout: {:?}\nstderr: {}",
            out.status.code(),
            out.stdout,
            String::from_utf8_lossy(&out.stderr),
        );
    }
}

fn assert_invalid_proof(desc: &str, proof: &[u8]) {
    let prf = TempFile::create(proof);
    let out = run(&prf.path);
    if out.status.code() != Some(1) || !out.stdout.is_empty() {
        panic!(
            "[{desc}] malformed proof must exit 1 with empty stdout\n\
             status: {:?}\nstdout: {:?}\nstderr: {}",
            out.status.code(),
            out.stdout,
            String::from_utf8_lossy(&out.stderr),
        );
    }
    let err = String::from_utf8_lossy(&out.stderr);
    if !err.contains("invalid proof") {
        panic!("[{desc}] stderr must name the format problem, got: {err}");
    }
}

#[test]
fn inspect_prints_claimed_fields_of_real_prove_output() {
    // The proof comes from the real `prove` command over the fixed batch;
    // the expected line is pinned to the independent constants above.
    let batch = TempFile::create(PAYLOAD_B9);
    let proved = Command::new(common::bin())
        .arg("prove")
        .arg(&batch.path)
        .arg("4")
        .output()
        .expect("failed to execute roottrace binary");
    assert_eq!(proved.status.code(), Some(0), "{:?}", proved.stderr);

    assert_inspect_ok("prove output as-is", &proved.stdout, EXPECTED_B9_M4_LINE);

    // The same proof rebuilt from the fixed constants must display the same.
    let fixed = proof_json(9, 4, ROOT_B9, PATH_B9_M4);
    assert_inspect_ok("fixed constant proof", fixed.as_bytes(), EXPECTED_B9_M4_LINE);
}

#[test]
fn inspect_accepts_reordered_whitespace_and_escaped_forms() {
    // Field reordering, legal JSON whitespace and equivalent \uXXXX escapes
    // (of field names and of hash characters) must not change the display.
    let pretty = format!(
        "  {{\n  \"audit_path\" : [ \"{}\",\n\t\"{}\", \"{}\" , \"{}\" ] ,\n  \"root\": \"{}\",\n  \"leaf_index\": 4 , \"tree_size\": 9\n}}\n",
        PATH_B9_M4[0], PATH_B9_M4[1], PATH_B9_M4[2], PATH_B9_M4[3], ROOT_B9,
    );
    assert_inspect_ok("pretty reordered", pretty.as_bytes(), EXPECTED_B9_M4_LINE);

    // "tree_siz\u0065" decodes to "tree_size"; the first root character 'a'
    // is spelled "\u0061" (uppercase hex inside the escape is legal).
    let escaped = format!(
        "{{\"tree_siz\\u0065\":9,\"leaf_index\":4,\"root\":\"\\u0061{}\",\"audit_path\":[\"{}\",\"{}\",\"{}\",\"{}\"]}}",
        &ROOT_B9[1..],
        PATH_B9_M4[0],
        PATH_B9_M4[1],
        PATH_B9_M4[2],
        PATH_B9_M4[3],
    );
    assert_inspect_ok("unicode-escaped", escaped.as_bytes(), EXPECTED_B9_M4_LINE);
}

#[test]
fn inspect_does_not_verify_the_audit_path() {
    // The hashes are all well-formed 64-char lowercase hex, but the path
    // cannot establish the claimed position: one hash's content is altered,
    // one proof drops a hash, one adds a hash, one swaps two. inspect has no
    // target record and no trusted values, so all of these still display —
    // and none of the output may claim verification.
    let mut flipped = PATH_B9_M4[0].to_string();
    flipped.replace_range(0..1, if flipped.starts_with('4') { "5" } else { "4" });
    let altered = proof_json(9, 4, ROOT_B9, &[&flipped, PATH_B9_M4[1], PATH_B9_M4[2], PATH_B9_M4[3]]);
    let short = proof_json(9, 4, ROOT_B9, &PATH_B9_M4[..3]);
    let long = proof_json(
        9,
        4,
        ROOT_B9,
        &[PATH_B9_M4[0], PATH_B9_M4[1], PATH_B9_M4[2], PATH_B9_M4[3], PATH_B9_M4[0]],
    );
    let swapped = proof_json(9, 4, ROOT_B9, &[PATH_B9_M4[1], PATH_B9_M4[0], PATH_B9_M4[2], PATH_B9_M4[3]]);
    for (desc, proof) in [
        ("altered hash", altered),
        ("short path", short),
        ("long path", long),
        ("swapped order", swapped),
    ] {
        let prf = TempFile::create(proof.as_bytes());
        let out = run(&prf.path);
        assert_eq!(out.status.code(), Some(0), "[{desc}] {:?}", out.stderr);
        assert_eq!(out.stdout, EXPECTED_B9_M4_LINE.as_bytes(), "[{desc}]");
        assert!(out.stderr.is_empty(), "[{desc}]");
        // The display is a claim, never a verification result.
        assert!(
            !out.stdout.windows(8).any(|w| w == b"verified"),
            "[{desc}] inspect output must not claim verification"
        );
    }
}

#[test]
fn inspect_rejects_corruption_anywhere_including_the_undisplayed_path() {
    let good = proof_json(9, 4, ROOT_B9, PATH_B9_M4);

    // A hash of the wrong length and an unterminated array inside the
    // never-displayed audit_path are still format errors.
    let bad_hash = proof_json(9, 4, ROOT_B9, &["abc", PATH_B9_M4[1], PATH_B9_M4[2], PATH_B9_M4[3]]);
    assert_invalid_proof("short hash in audit_path", bad_hash.as_bytes());

    let mut unterminated = good.clone();
    unterminated.truncate(unterminated.len() - 2); // drop `"]}` , array never closes
    assert_invalid_proof("unterminated audit_path", unterminated.as_bytes());

    // An uppercase hash character inside audit_path.
    let upper = proof_json(9, 4, ROOT_B9, &[&PATH_B9_M4[0].to_uppercase(), PATH_B9_M4[1], PATH_B9_M4[2], PATH_B9_M4[3]]);
    assert_invalid_proof("uppercase hash in audit_path", upper.as_bytes());

    // Truncation at every cut point of the whole proof.
    for cut in 0..good.len() {
        assert_invalid_proof("truncated proof", &good.as_bytes()[..cut]);
    }

    // Trailing bytes after the object.
    let mut trailing = good.clone().into_bytes();
    trailing.extend_from_slice(b" {}");
    assert_invalid_proof("trailing data", &trailing);
}

#[test]
fn inspect_rejects_duplicates_zero_size_and_out_of_range_index() {
    // Duplicate fields, including a duplicate that only appears after
    // escape decoding ("\u0069udit_path" == "audit_path"... spelled on
    // tree_size here: "tree_siz\u0065").
    let dup_plain = format!(
        "{{\"tree_size\":9,\"tree_size\":9,\"leaf_index\":4,\"root\":\"{ROOT_B9}\",\"audit_path\":[]}}"
    );
    assert_invalid_proof("plain duplicate", dup_plain.as_bytes());
    let dup_escaped = format!(
        "{{\"tree_size\":9,\"tree_siz\\u0065\":9,\"leaf_index\":4,\"root\":\"{ROOT_B9}\",\"audit_path\":[]}}"
    );
    assert_invalid_proof("escaped duplicate", dup_escaped.as_bytes());

    // tree_size 0 and an index at or past the claimed size stay rejected.
    let zero = format!("{{\"tree_size\":0,\"leaf_index\":0,\"root\":\"{ROOT_B9}\",\"audit_path\":[]}}");
    assert_invalid_proof("tree_size 0", zero.as_bytes());
    let oob = format!("{{\"tree_size\":9,\"leaf_index\":9,\"root\":\"{ROOT_B9}\",\"audit_path\":[]}}");
    assert_invalid_proof("leaf_index out of range", oob.as_bytes());

    // Missing fields are format errors too: finding the three displayed
    // fields is not enough.
    let no_path = format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"{ROOT_B9}\"}}");
    assert_invalid_proof("missing audit_path", no_path.as_bytes());
    let no_index = format!(
        "{{\"tree_size\":9,\"root\":\"{ROOT_B9}\",\"audit_path\":[\"{}\"]}}",
        PATH_B9_M4[0]
    );
    assert_invalid_proof("missing leaf_index", no_index.as_bytes());
}

#[test]
fn inspect_keeps_full_64bit_meaning_of_size_and_index() {
    // A synthetically large but format-valid proof: the integers must be
    // displayed with their full 64-bit unsigned values, not truncated.
    let size = u64::MAX;
    let index = u64::MAX - 1;
    let proof = format!(
        "{{\"tree_size\":{size},\"leaf_index\":{index},\"root\":\"{ROOT_B9}\",\"audit_path\":[]}}"
    );
    let expected = format!(
        "{{\"tree_size\":18446744073709551615,\"leaf_index\":18446744073709551614,\"root\":\"{ROOT_B9}\"}}\n"
    );
    assert_inspect_ok("u64 extremes", proof.as_bytes(), &expected);

    // An index equal to the (huge) size is out of range, not wrapped.
    let oob = format!(
        "{{\"tree_size\":{size},\"leaf_index\":{size},\"root\":\"{ROOT_B9}\",\"audit_path\":[]}}"
    );
    assert_invalid_proof("index == size at u64::MAX", oob.as_bytes());
}

#[test]
fn inspect_read_failures_exit_1_with_empty_stdout() {
    let missing = std::env::temp_dir().join(format!(
        "roottrace-inspect-no-such-{}-proof.json",
        std::process::id()
    ));
    let out = run(&missing);
    assert_eq!(out.status.code(), Some(1));
    assert!(out.stdout.is_empty());
    assert!(
        String::from_utf8_lossy(&out.stderr).contains("cannot read"),
        "{:?}",
        out.stderr
    );

    let dir = TempDir::create();
    let out = run(&dir.path);
    assert_eq!(out.status.code(), Some(1));
    assert!(out.stdout.is_empty());
    assert!(
        String::from_utf8_lossy(&out.stderr).contains("cannot read"),
        "{:?}",
        out.stderr
    );
}

#[test]
fn inspect_argument_errors_exit_2_with_usage() {
    let proof = TempFile::create(proof_json(9, 4, ROOT_B9, PATH_B9_M4).as_bytes());
    // No proof-file argument at all, and one argument too many.
    let missing = Command::new(common::bin())
        .arg("inspect")
        .output()
        .expect("failed to execute roottrace binary");
    assert_eq!(missing.status.code(), Some(2));
    assert!(missing.stdout.is_empty());
    assert!(String::from_utf8_lossy(&missing.stderr).contains("Usage"));

    let extra = Command::new(common::bin())
        .arg("inspect")
        .arg(&proof.path)
        .arg("extra")
        .output()
        .expect("failed to execute roottrace binary");
    assert_eq!(extra.status.code(), Some(2));
    assert!(extra.stdout.is_empty());
    assert!(String::from_utf8_lossy(&extra.stderr).contains("Usage"));
}

/// A proof file whose name contains bytes that are not valid UTF-8 must be
/// opened by its raw path bytes, exactly like the other commands.
#[cfg(unix)]
#[test]
fn inspect_accepts_non_utf8_proof_path() {
    use std::os::unix::ffi::OsStrExt;

    let dir = TempDir::create();
    let weird = dir.path.join(std::ffi::OsStr::from_bytes(b"proof-\xff.json"));
    std::fs::write(&weird, proof_json(9, 4, ROOT_B9, PATH_B9_M4).as_bytes()).unwrap();

    let out = run(&weird);
    assert_eq!(out.status.code(), Some(0), "{:?}", out.stderr);
    assert_eq!(out.stdout, EXPECTED_B9_M4_LINE.as_bytes());
    assert!(out.stderr.is_empty());

    // A missing non-UTF-8 path keeps the read-failure contract.
    let missing = dir.path.join(std::ffi::OsStr::from_bytes(b"no-such-\xff.json"));
    let out = run(&missing);
    assert_eq!(out.status.code(), Some(1));
    assert!(out.stdout.is_empty());
    assert!(!out.stderr.is_empty());
}
