//! End-to-end regression tests for file paths that are NOT valid UTF-8.
//!
//! On Unix a filename or parent-directory name may contain arbitrary bytes
//! (other than NUL and '/'), including an isolated byte such as 0xff that can
//! never start a UTF-8 sequence. Such a path is still a real path: it must be
//! handed to the filesystem byte for byte. These tests pin down that:
//!
//!   * `root`/`prove` read a file whose own name contains 0xff, given as a
//!     relative or an absolute path, and produce the same results as for a
//!     plain-named file holding the same bytes;
//!   * a sibling whose name contains the Unicode replacement character U+FFFD
//!     (UTF-8 EF BF BD, what a lossy display of the 0xff name would show) is a
//!     DIFFERENT file and must never be read by mistake;
//!   * identical contents under byte-different (even non-UTF-8) path names
//!     give identical results — the path bytes never enter the hash;
//!   * a non-UTF-8 parent-directory name works as well;
//!   * a missing path or a directory whose name contains non-UTF-8 bytes is a
//!     stable exit-1 read failure (empty stdout, message on stderr), never a
//!     panic and never a usage error;
//!   * non-UTF-8 bytes in the command name or record index remain usage
//!     errors (exit 2, usage on stderr, empty stdout).
//!
//! The whole module is Unix-only: on other platforms argv bytes are not
//! addressable independently of UTF-8, and the non-UTF-8 filename premise does
//! not apply.

#![cfg(unix)]

mod common;

use std::fs;
use std::os::unix::ffi::{OsStrExt, OsStringExt};
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU64, Ordering};

use common::join_lf;

// The same 9-record uneven batch and fixed vectors used by the other
// regression suites (independently generated by
// tests/reference/rfc6962_vectors.py), so a correct read through a non-UTF-8
// path must reproduce these exact bytes.
const B9: &[&[u8]] = &[
    b"alpha",
    b"beta",
    b"",
    b"gamma",
    b"alpha",
    b"delta\r",
    b"\xff\xfe\x00binary",
    b"epsilon",
    b"zeta\x01tail",
];
const ROOT_B9: &str = "a8a3e76ecf28b850e84cb5465729921212ffd07de3c0e6e170cd233bf723adc3";
const ROOT_B8: &str = "80f3f98ae8d7d9d1d2139a6a2dc94628e02fba22e125f922ea8a4c10799cb912";

// Fixed inclusion proof for B9 at index 4 (byte-equal duplicate of index 0),
// copied from prove_regression / the reference generator.
const PROOF_B9_M4: &str = concat!(
    "{\"tree_size\":9,\"leaf_index\":4,\"root\":\"",
    "a8a3e76ecf28b850e84cb5465729921212ffd07de3c0e6e170cd233bf723adc3",
    "\",\"audit_path\":[",
    "\"4957faa551907820ed93a476704ffd826ea5502881876c87f3acefc0a8d29bce\",",
    "\"b739bc437ae5d551d144d1478ee16d1119ba15b2198a3a8b7c47976c36cb6639\",",
    "\"6f2bd73a7406c5089558c115aaae63a717e4c6947c44898e7d9600023ff15d10\",",
    "\"5cc496b84d9250622d5de1219d1f156e7973503fbd80f7f3364800bbfa2947d2\"",
    "]}",
);

fn os(bytes: &[u8]) -> std::ffi::OsString {
    std::ffi::OsString::from_vec(bytes.to_vec())
}

/// Temporary directory removed wholesale on drop; its entries may have names
/// that are not valid UTF-8.
struct TempDir {
    path: PathBuf,
}

static COUNTER: AtomicU64 = AtomicU64::new(0);

impl TempDir {
    fn create() -> Self {
        let id = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "roottrace-nonutf8-{}-{}",
            std::process::id(),
            id
        ));
        fs::create_dir(&path).unwrap_or_else(|e| panic!("create {}: {e}", path.display()));
        TempDir { path }
    }

    /// Join a relative name that may itself contain non-UTF-8 bytes.
    fn child(&self, rel: &[u8]) -> PathBuf {
        let mut full = self.path.clone().into_os_string();
        full.push("/");
        full.push(std::ffi::OsStr::from_bytes(rel));
        PathBuf::from(full)
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.path);
    }
}

fn run(args: Vec<std::ffi::OsString>, dir: Option<&Path>) -> Output {
    let mut cmd = Command::new(common::bin());
    cmd.args(args);
    if let Some(dir) = dir {
        cmd.current_dir(dir);
    }
    cmd.output().expect("failed to execute roottrace binary")
}

fn root_at(path: &[u8], relative_to: Option<&Path>) -> Output {
    run(vec![os(b"root"), os(path)], relative_to)
}

fn prove_at(path: &[u8], index: &[u8], relative_to: Option<&Path>) -> Output {
    run(vec![os(b"prove"), os(path), os(index)], relative_to)
}

fn stdout_line(out: &Output) -> String {
    String::from_utf8(out.stdout.clone()).expect("success stdout is ASCII hex/JSON + LF")
}

#[test]
fn root_reads_file_whose_name_contains_0xff() {
    let dir = TempDir::create();
    let weird = dir.child(b"bad\xffname");
    fs::write(&weird, join_lf(B9, true)).unwrap();
    let plain = dir.child(b"plain-name");
    fs::write(&plain, join_lf(B9, true)).unwrap();

    // Absolute path through the non-UTF-8 name.
    let out = root_at(weird.as_os_str().as_encoded_bytes(), None);
    assert_eq!(
        out.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(out.stderr.is_empty());
    assert_eq!(stdout_line(&out).trim_end_matches('\n'), ROOT_B9);

    // The plain-named file with the same contents hashes identically.
    let out_plain = root_at(plain.as_os_str().as_encoded_bytes(), None);
    assert_eq!(out_plain.status.code(), Some(0));
    assert_eq!(out_plain.stdout, out.stdout, "path bytes must not affect the root");
}

#[test]
fn root_and_prove_accept_relative_non_utf8_path() {
    let dir = TempDir::create();
    let weird = dir.child(b"batch\xff.txt");
    fs::write(&weird, join_lf(B9, true)).unwrap();

    // Relative path: run with cwd set to the temp directory.
    let out = root_at(b"batch\xff.txt", Some(&dir.path));
    assert_eq!(
        out.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(out.stderr.is_empty());
    assert_eq!(stdout_line(&out).trim_end_matches('\n'), ROOT_B9);

    let proof = prove_at(b"batch\xff.txt", b"4", Some(&dir.path));
    assert_eq!(
        proof.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&proof.stderr)
    );
    assert!(proof.stderr.is_empty());
    assert_eq!(
        stdout_line(&proof).trim_end_matches('\n'),
        PROOF_B9_M4,
        "proof must bind the requested position and the whole B9 batch"
    );
}

#[test]
fn replacement_character_sibling_is_a_distinct_file() {
    // "bad\xffname" displayed lossily looks like "bad\u{FFFD}name", which is
    // exactly the UTF-8 name EF BF BD. Both files exist side by side; they
    // hold different content, and each must be addressed independently.
    let dir = TempDir::create();
    let raw_ff = dir.child(b"bad\xffname");
    let replacement = dir.child(b"bad\xef\xbf\xbdname");
    fs::write(&raw_ff, join_lf(B9, true)).unwrap();
    fs::write(&replacement, b"DECOY\n").unwrap();
    // A plain-named copy of the decoy content for an independent expected
    // root reference.
    let decoy_plain = dir.child(b"decoy-copy");
    fs::write(&decoy_plain, b"DECOY\n").unwrap();

    let via_ff = root_at(raw_ff.as_os_str().as_encoded_bytes(), None);
    let via_repl = root_at(replacement.as_os_str().as_encoded_bytes(), None);
    let via_decoy = root_at(decoy_plain.as_os_str().as_encoded_bytes(), None);
    assert_eq!(via_ff.status.code(), Some(0));
    assert_eq!(via_repl.status.code(), Some(0));
    assert_eq!(via_decoy.status.code(), Some(0));

    assert_eq!(stdout_line(&via_ff).trim_end_matches('\n'), ROOT_B9);
    assert_ne!(
        stdout_line(&via_repl).trim_end_matches('\n'),
        ROOT_B9,
        "must not follow the lossy-looking name to the U+FFFD sibling"
    );
    assert_eq!(
        via_repl.stdout, via_decoy.stdout,
        "the U+FFFD-named file must itself be readable and hold the decoy content"
    );
    assert_ne!(via_ff.stdout, via_repl.stdout);
}

#[test]
fn same_content_under_byte_different_non_utf8_paths_hashes_the_same() {
    let dir = TempDir::create();
    let payload = b"same-content\n";
    fs::write(dir.child(b"one\xffname"), payload).unwrap();
    fs::write(dir.child(b"two\xfename"), payload).unwrap();
    fs::write(dir.child(b"three\xc0name"), payload).unwrap();
    fs::write(dir.child(b"plain-name"), payload).unwrap();

    let a = root_at(dir.child(b"one\xffname").as_os_str().as_encoded_bytes(), None);
    let b = root_at(dir.child(b"two\xfename").as_os_str().as_encoded_bytes(), None);
    let c = root_at(dir.child(b"three\xc0name").as_os_str().as_encoded_bytes(), None);
    let d = root_at(dir.child(b"plain-name").as_os_str().as_encoded_bytes(), None);
    for (label, out) in [("ff", &a), ("fe", &b), ("c0", &c), ("plain", &d)] {
        assert_eq!(
            out.status.code(),
            Some(0),
            "{label}: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        assert!(out.stderr.is_empty(), "{label}");
    }
    assert_eq!(a.stdout, b.stdout);
    assert_eq!(a.stdout, c.stdout);
    assert_eq!(a.stdout, d.stdout, "non-UTF-8 and ASCII path names give the same root");
}

#[test]
fn non_utf8_parent_directory_name_works_relative_and_absolute() {
    let dir = TempDir::create();
    let sub = dir.child(b"sub\xffdir");
    fs::create_dir(&sub).unwrap();
    let batch = PathBuf::from(&sub).join("batch.txt");
    fs::write(&batch, join_lf(B9, true)).unwrap();

    // Absolute form, non-UTF-8 component in a parent directory.
    let abs = root_at(batch.as_os_str().as_encoded_bytes(), None);
    assert_eq!(
        abs.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&abs.stderr)
    );
    assert_eq!(stdout_line(&abs).trim_end_matches('\n'), ROOT_B9);

    // Relative form descending into the non-UTF-8 directory.
    let rel = root_at(b"sub\xffdir/batch.txt", Some(&dir.path));
    assert_eq!(
        rel.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&rel.stderr)
    );
    assert_eq!(rel.stdout, abs.stdout);

    // prove through the non-UTF-8 parent directory.
    let proof = prove_at(b"sub\xffdir/batch.txt", b"8", Some(&dir.path));
    assert_eq!(
        proof.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&proof.stderr)
    );
    assert!(proof.stderr.is_empty());
    // Last record of the uneven 9-record tree: one sibling equal to ROOT_B8.
    let line = stdout_line(&proof);
    assert!(line.contains("\"leaf_index\":8"));
    assert!(line.contains(&format!("\"root\":\"{ROOT_B9}\"")));
    assert!(line.contains(&format!("\"{ROOT_B8}\"")));
}

#[test]
fn missing_non_utf8_path_is_a_stable_read_failure_exit_1() {
    let dir = TempDir::create();
    // Ensure a replacement-named sibling exists, so only the 0xff name is
    // missing and a lossy display cannot accidentally resolve to it.
    fs::write(dir.child(b"gone\xef\xbf\xbdname"), b"x").unwrap();

    for cmd in [b"root".as_slice(), b"prove".as_slice()] {
        let mut args = vec![os(cmd), os(b"gone\xffname")];
        if cmd == b"prove" {
            args.push(os(b"0"));
        }
        let out = run(args, Some(&dir.path));
        assert_eq!(out.status.code(), Some(1), "cmd {cmd:?}: expected exit 1");
        assert!(out.stdout.is_empty(), "cmd {cmd:?}: nothing on stdout");
        let err = String::from_utf8_lossy(&out.stderr);
        assert!(
            err.contains("cannot read"),
            "cmd {cmd:?}: stderr must report the read failure: {err}"
        );
        assert!(
            err.contains('\u{FFFD}'),
            "cmd {cmd:?}: undisplayable bytes render stably as U+FFFD: {err}"
        );
    }
}

#[test]
fn directory_with_non_utf8_name_exits_1() {
    let dir = TempDir::create();
    let sub = dir.child(b"a\xffdirectory");
    fs::create_dir(&sub).unwrap();

    let root = root_at(sub.as_os_str().as_encoded_bytes(), None);
    assert_eq!(root.status.code(), Some(1));
    assert!(root.stdout.is_empty());
    assert!(String::from_utf8_lossy(&root.stderr).contains("cannot read"));

    let prove = prove_at(sub.as_os_str().as_encoded_bytes(), b"0", None);
    assert_eq!(prove.status.code(), Some(1));
    assert!(prove.stdout.is_empty());
    assert!(String::from_utf8_lossy(&prove.stderr).contains("cannot read"));
}

#[test]
fn non_utf8_command_name_and_index_are_usage_errors_exit_2() {
    let dir = TempDir::create();
    let batch = dir.child(b"batch\xff");
    fs::write(&batch, join_lf(B9, true)).unwrap();
    let path_bytes = batch.as_os_str().as_encoded_bytes();

    // Non-UTF-8 command name: unknown command, usage error.
    let out = run(vec![os(b"r\xffot"), os(path_bytes)], None);
    assert_eq!(out.status.code(), Some(2));
    assert!(out.stdout.is_empty());
    assert!(String::from_utf8_lossy(&out.stderr).contains("Usage"));

    // Non-UTF-8 record index: bad index, usage error (even though digits
    // surround the bad byte and would otherwise name a valid position).
    for bad in [b"1\xff".as_slice(), b"\xff".as_slice(), b"0\xff".as_slice()] {
        let out = run(vec![os(b"prove"), os(path_bytes), os(bad)], None);
        assert_eq!(out.status.code(), Some(2), "index {bad:?} must exit 2");
        assert!(out.stdout.is_empty(), "index {bad:?} must not write stdout");
        let err = String::from_utf8_lossy(&out.stderr);
        assert!(err.contains("Usage"), "index {bad:?} must print usage, got: {err}");
    }
}
