//! End-to-end regression tests: a record whose CONTENT contains LF bytes
//! still verifies as ONE complete record — for the CLI (`roottrace verify`,
//! whose record file is all bytes of the record, never LF-split) and for
//! the library (`roottrace::verify_membership`, whose record slice follows
//! the same byte rule).
//!
//! Such a record cannot be expressed in a root/prove batch file (LF is the
//! record separator there), so nothing here is produced by roottrace: the
//! fixed record bytes, roots and audit paths below are generated by
//! `tests/reference/rfc6962_vectors.py`, which computes them with two
//! structurally different RFC 6962 implementations that must agree and
//! re-verifies every proof back to the tree root with an independent
//! recursive verifier. The trusted tree sizes and roots play the role of
//! values confirmed over an independent channel.
//!
//! Coverage:
//!   * an LF-laden record (leading LF, consecutive LFs inside, trailing
//!     LF, plus CR/NUL/non-UTF-8 bytes, 70 bytes so the leaf input crosses
//!     the 64-byte SHA-256 block boundary) verifies in a single-record
//!     tree (empty audit path) and in an uneven 9-record tree
//!   * a record that is exactly one LF verifies, and is neither the
//!     zero-byte empty record nor the empty record a batch file denotes
//!   * success output is exactly "verified\n", exit 0, empty stderr; the
//!     library result carries the claimed index and the trusted size/root
//!   * dropping the trailing LF or changing one internal LF (all other
//!     bytes kept) fails as VERIFICATION FAILED (exit 1, empty stdout),
//!     never as an invalid proof and never as success — CLI and library
//!   * no single LF-separated "line" of the record verifies in its place

mod common;

use std::process::Command;

use common::TempFile;
use roottrace::{verify_membership, VerifyError};

// --- Fixed constants (copied from the reference generator) -----------------

/// 70 bytes: LF + tag with NUL/non-UTF-8/CR + three consecutive LFs + ASCII
/// fill + trailing LF. Leaf input 0x00 || record is 71 bytes, crossing the
/// 64-byte SHA-256 block boundary.
const REC_LF: &[u8] = b"\nLF:\x00\xff\xfe\r\n\n\nabcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuv\n";
/// A record that is exactly one LF.
const REC_ONE_LF: &[u8] = b"\n";

const ROOT_LF_REC_SINGLE: &str = "2852eabb5578f4e09640fe4ee4734814ba9caec330a71cb43f8533b335b5038c";
const ROOT_ONE_LF_REC_SINGLE: &str = "67ebbd370daa02ba9aadd05d8e091e862d0d8bcadafdf2a22360240a42fe922e";
const ROOT_LF9: &str = "440aac54279c27539a0cdc3279c3ed052e51d4bb1e9e8ac2089a8d0d370cc0bd";
/// Root of the one-empty-record tree (SHA-256(0x00)); the batch-file empty
/// record the one-LF record must stay distinct from.
const ROOT_ONE_EMPTY_RECORD: &str =
    "6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d";

const PATH_LF9_M2: &[&str] = &[
    "4c79d0d62f7cf5ca8874155f2d3b875f2625da2bb3abc86bbd6833f25ba90e51",
    "e5c500d4e9f2bd311da87658fd66f03d1aaeb85e92844381550935c5a9d99db3",
    "4b3c0c0b8daff1cbec3e2142fc8d784032aa3c400c25e819ece0251bbc615b04",
    "5cc496b84d9250622d5de1219d1f156e7973503fbd80f7f3364800bbfa2947d2",
];
const PATH_LF9_M5: &[&str] = &[
    "be804050d01985da4bc94040706fbea527f69da217523866faf240fb1d80a1f1",
    "0b38129412c998a9982da158b26548fa671d9f1b51ab163500a268fd4412d336",
    "8e844ebe39d09bc92941bc67f663dade5994f92513988b29626c8d7be0e01fd4",
    "5cc496b84d9250622d5de1219d1f156e7973503fbd80f7f3364800bbfa2947d2",
];

fn proof_json(size: u64, index: u64, root: &str, path: &[&str]) -> Vec<u8> {
    let mut out =
        format!("{{\"tree_size\":{size},\"leaf_index\":{index},\"root\":\"{root}\",\"audit_path\":[");
    for (i, h) in path.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        out.push('"');
        out.push_str(h);
        out.push('"');
    }
    out.push_str("]}");
    out.into_bytes()
}

/// The four fixed (record, proof, trusted size, trusted root) combinations
/// an external system would hand over for the LF-containing records; the
/// u64 is the leaf index the proof declares.
fn fixed_cases() -> Vec<(&'static str, &'static [u8], Vec<u8>, u64, &'static str, u64)> {
    vec![
        ("LF record, single-record tree", REC_LF, proof_json(1, 0, ROOT_LF_REC_SINGLE, &[]), 1, ROOT_LF_REC_SINGLE, 0),
        ("LF record, 9-record tree at m=5", REC_LF, proof_json(9, 5, ROOT_LF9, PATH_LF9_M5), 9, ROOT_LF9, 5),
        ("one-LF record, single-record tree", REC_ONE_LF, proof_json(1, 0, ROOT_ONE_LF_REC_SINGLE, &[]), 1, ROOT_ONE_LF_REC_SINGLE, 0),
        ("one-LF record, 9-record tree at m=2", REC_ONE_LF, proof_json(9, 2, ROOT_LF9, PATH_LF9_M2), 9, ROOT_LF9, 2),
    ]
}

// --- CLI assertions ----------------------------------------------------------

fn run_verify(record: &[u8], proof: &[u8], size: u64, root: &str) -> std::process::Output {
    let rec = TempFile::create(record);
    let prf = TempFile::create(proof);
    Command::new(common::bin())
        .arg("verify")
        .arg(&rec.path)
        .arg(&prf.path)
        .arg(size.to_string())
        .arg(root)
        .output()
        .expect("failed to execute roottrace binary")
}

fn assert_verified(desc: &str, record: &[u8], proof: &[u8], size: u64, root: &str) {
    let out = run_verify(record, proof, size, root);
    assert_eq!(out.status.code(), Some(0), "[{desc}] must exit 0: {}", String::from_utf8_lossy(&out.stderr));
    assert_eq!(out.stdout, b"verified\n", "[{desc}] stdout must be exactly \"verified\\n\"");
    assert!(out.stderr.is_empty(), "[{desc}] stderr must be empty: {}", String::from_utf8_lossy(&out.stderr));
}

fn assert_verification_failed(desc: &str, record: &[u8], proof: &[u8], size: u64, root: &str) {
    let out = run_verify(record, proof, size, root);
    assert_eq!(out.status.code(), Some(1), "[{desc}] must exit 1");
    assert!(out.stdout.is_empty(), "[{desc}] stdout must be empty, got {:?}", out.stdout);
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("verification failed"), "[{desc}] must be a verification failure: {err}");
    assert!(!err.contains("invalid proof"), "[{desc}] must not be classed as an invalid proof: {err}");
}

// --- Library assertions ------------------------------------------------------

/// Decode 64 lowercase hex characters into a 32-byte hash.
fn hash_of(hex: &str) -> [u8; 32] {
    assert_eq!(hex.len(), 64, "hash must be 64 hex chars: {hex:?}");
    let mut out = [0u8; 32];
    for (i, pair) in hex.as_bytes().chunks_exact(2).enumerate() {
        let nibble = |b: u8| -> u8 {
            match b {
                b'0'..=b'9' => b - b'0',
                b'a'..=b'f' => b - b'a' + 10,
                _ => panic!("not lowercase hex: {hex:?}"),
            }
        };
        out[i] = (nibble(pair[0]) << 4) | nibble(pair[1]);
    }
    out
}

fn assert_lib_verified(desc: &str, record: &[u8], proof: &[u8], size: u64, root: &str, index: u64) {
    let trusted_root = hash_of(root);
    let m = verify_membership(record, proof, size, &trusted_root)
        .unwrap_or_else(|e| panic!("[{desc}] must verify: {e}"));
    assert_eq!(m.leaf_index(), index, "[{desc}] claimed position");
    assert_eq!(m.tree_size(), size, "[{desc}] trusted tree size");
    assert_eq!(m.root(), &trusted_root, "[{desc}] trusted root");
}

fn assert_lib_verification_failed(desc: &str, record: &[u8], proof: &[u8], size: u64, root: &str) {
    match verify_membership(record, proof, size, &hash_of(root)) {
        Err(VerifyError::VerificationFailed(_)) => {}
        other => panic!("[{desc}] must be VerificationFailed, got {other:?}"),
    }
}

// --- Success: every LF in the record is content ------------------------------

#[test]
fn lf_content_record_verifies_as_one_complete_record() {
    for (desc, record, proof, size, root, index) in fixed_cases() {
        assert_verified(desc, record, &proof, size, root);
        assert_lib_verified(desc, record, &proof, size, root, index);
    }
}

#[test]
fn lf_bytes_do_not_change_the_claimed_tree_size_or_position() {
    // The proof for the 9-record tree keeps declaring tree_size 9 and the
    // target position; the record's internal LFs add no records to the tree
    // and move no index. Trusted values from a neighbouring size or position
    // must fail.
    let proof = proof_json(9, 5, ROOT_LF9, PATH_LF9_M5);
    assert_verification_failed("trusted size 10 vs proof 9", REC_LF, &proof, 10, ROOT_LF9);
    assert_verification_failed("trusted size 8 vs proof 9", REC_LF, &proof, 8, ROOT_LF9);
    // The same record reclaimed at a position that holds other bytes fails.
    let moved = proof_json(9, 0, ROOT_LF9, PATH_LF9_M5);
    assert_verification_failed("LF record mislabeled as index 0", REC_LF, &moved, 9, ROOT_LF9);
    assert_lib_verification_failed("library: trusted size 10", REC_LF, &proof, 10, ROOT_LF9);
    assert_lib_verification_failed("library: mislabeled index 0", REC_LF, &moved, 9, ROOT_LF9);
}

#[test]
fn no_single_lf_separated_line_of_the_record_verifies() {
    // Verification must not fall back to matching one "line" of the record.
    // REC_LF starts with LF, so its first line is empty; the consecutive
    // LFs surround more empty pieces; the fill content is another piece.
    let proof = proof_json(9, 5, ROOT_LF9, PATH_LF9_M5);
    let single = proof_json(1, 0, ROOT_LF_REC_SINGLE, &[]);
    let pieces: &[&[u8]] = &[
        b"",           // the empty "line" before the leading LF
        b"LF:\x00\xff\xfe\r", // the tag line between LF runs
        b"abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuv", // the fill line
    ];
    for piece in pieces {
        assert_verification_failed("one line of the record, 9-record tree", piece, &proof, 9, ROOT_LF9);
        assert_verification_failed("one line of the record, single tree", piece, &single, 1, ROOT_LF_REC_SINGLE);
        assert_lib_verification_failed("library: one line of the record", piece, &proof, 9, ROOT_LF9);
    }
}

// --- Tampering with the record's LF bytes fails as verification failure ----

#[test]
fn dropping_the_trailing_lf_fails_verification() {
    // The trailing LF is content, not a record terminator: without it the
    // record is a different (69-byte) record.
    let shortened = &REC_LF[..REC_LF.len() - 1];
    assert_eq!(shortened.last(), Some(&b'v'));
    for (desc, _, proof, size, root, _) in fixed_cases() {
        if !desc.starts_with("LF record") {
            continue;
        }
        assert_verification_failed("trailing LF dropped", shortened, &proof, size, root);
        assert_lib_verification_failed("library: trailing LF dropped", shortened, &proof, size, root);
    }
}

#[test]
fn changing_one_internal_lf_fails_verification() {
    // Index 9 is the middle LF of the consecutive run; replace it with 'X',
    // keeping every other byte (length unchanged at 70).
    assert_eq!(REC_LF[9], b'\n');
    let mut swapped = REC_LF.to_vec();
    swapped[9] = b'X';
    assert_eq!(swapped.len(), REC_LF.len());
    for (desc, _, proof, size, root, _) in fixed_cases() {
        if !desc.starts_with("LF record") {
            continue;
        }
        assert_verification_failed("one internal LF changed", &swapped, &proof, size, root);
        assert_lib_verification_failed("library: one internal LF changed", &swapped, &proof, size, root);
    }
}

// --- A record that is exactly one LF -----------------------------------------

#[test]
fn one_lf_record_is_neither_zero_bytes_nor_the_batch_file_empty_record() {
    let single = proof_json(1, 0, ROOT_ONE_LF_REC_SINGLE, &[]);
    let in_tree = proof_json(9, 2, ROOT_LF9, PATH_LF9_M2);

    // The one-LF record verifies against its own proofs (covered again here
    // for the contrast below).
    assert_verified("one LF, single-record tree", REC_ONE_LF, &single, 1, ROOT_ONE_LF_REC_SINGLE);
    assert_verified("one LF, 9-record tree", REC_ONE_LF, &in_tree, 9, ROOT_LF9);

    // It is not the zero-byte empty record: the empty record must not
    // verify against the one-LF record's proofs, and the roots differ.
    assert_ne!(ROOT_ONE_LF_REC_SINGLE, ROOT_ONE_EMPTY_RECORD);
    assert_verification_failed("zero-byte record vs one-LF proof (single)", b"", &single, 1, ROOT_ONE_LF_REC_SINGLE);
    assert_verification_failed("zero-byte record vs one-LF proof (9-tree)", b"", &in_tree, 9, ROOT_LF9);
    assert_lib_verification_failed("library: zero-byte record vs one-LF proof", b"", &single, 1, ROOT_ONE_LF_REC_SINGLE);

    // Nor is it the empty record a batch file denotes: the one-LF record
    // must not verify against the one-empty-record tree's proof.
    let empty_record_proof = proof_json(1, 0, ROOT_ONE_EMPTY_RECORD, &[]);
    assert_verification_failed("one-LF record vs empty-record proof", REC_ONE_LF, &empty_record_proof, 1, ROOT_ONE_EMPTY_RECORD);
    assert_lib_verification_failed("library: one-LF record vs empty-record proof", REC_ONE_LF, &empty_record_proof, 1, ROOT_ONE_EMPTY_RECORD);

    // Two LFs are yet another record, not "the one-LF record plus a
    // terminator".
    assert_verification_failed("two LFs vs one-LF proof", b"\n\n", &single, 1, ROOT_ONE_LF_REC_SINGLE);
    assert_lib_verification_failed("library: two LFs vs one-LF proof", b"\n\n", &single, 1, ROOT_ONE_LF_REC_SINGLE);
}
