//! End-to-end regression tests for
//! `roottrace verify <record-file> <proof-file> <trusted-tree-size> <trusted-root>`.
//!
//! The fixed proof vectors are the SAME independently produced constants used
//! by `prove_regression.rs` (generated by
//! `tests/reference/rfc6962_vectors.py`, which computes RFC 6962 audit paths
//! two structurally different ways and re-verifies them with `hashlib`); they
//! are never derived from roottrace output. Where a proof is needed for a
//! position without a fixed constant, the test runs `roottrace prove` and
//! feeds its output straight to `roottrace verify`, covering interop with the
//! existing command byte for byte.
//!
//! Coverage:
//!   * success: stdout is exactly "verified\n", exit 0, stderr empty
//!   * compact, pretty and field-reordered proof JSON all verify
//!   * the record file is taken verbatim: empty file = empty record, while a
//!     trailing LF/space/CR, NUL and non-UTF-8 differences change the record
//!   * the trusted size and root come ONLY from the command line and must
//!     match the proof; the proof's own fields cannot substitute
//!   * duplicate content is checked at the declared leaf_index only
//!   * short/long audit paths (incl. a non-empty path for a one-record tree)
//!     fail
//!   * malformed proofs exit 1 with an "invalid proof" message and no stdout
//!   * argument errors exit 2 with usage; read failures exit 1

mod common;

use std::process::Command;

use common::{TempDir, TempFile};

// --- Fixed payloads, roots and paths (copied from the reference generator) --

const PAYLOAD_B8: &[u8] =
    b"alpha\nbeta\n\ngamma\nalpha\ndelta\r\n\xff\xfe\x00binary\nepsilon\n";
const PAYLOAD_B9: &[u8] =
    b"alpha\nbeta\n\ngamma\nalpha\ndelta\r\n\xff\xfe\x00binary\nepsilon\nzeta\x01tail\n";
const PAYLOAD_ONE_LF: &[u8] = b"\n";
const PAYLOAD_MIXED: &[u8] = b"alpha\n\nL54:\x00\xff\xfe\rabcdefghijklmnopqrstuvwxyz0123456789abcdefghi\x00\nbeta\r\nL63:\x00\xff\xfe\rabcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqr\x00\n\xff\x00z\nL135:\x00\xff\xfe\rabcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopq\xff\nmiddle\nL65:\x00\xff\xfe\rabcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrst\xfe\nend-record\x01\n";

const ROOT_B8: &str = "80f3f98ae8d7d9d1d2139a6a2dc94628e02fba22e125f922ea8a4c10799cb912";
const ROOT_B9: &str = "a8a3e76ecf28b850e84cb5465729921212ffd07de3c0e6e170cd233bf723adc3";
const ROOT_ONE_EMPTY_RECORD: &str =
    "6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d";
const ROOT_MIXED: &str = "3a460e4bda163253da14917c2f9c63208d1b24e3d285c763d2f6c6dedec6694b";

const PATH_B9_M0: &[&str] = &[
    "e23537b050e84af2cbaab46f2f83d8d3b5febc8e5ac6200d306284f687d46924",
    "ac96b46d1760957393e22a8a365d54e58645a244550bc3c566892cdbdc5d8fc1",
    "416649c1a4f116151112df7d7d3faa85d5d8c60699e153e7a3c57a1abab7a242",
    "5cc496b84d9250622d5de1219d1f156e7973503fbd80f7f3364800bbfa2947d2",
];
const PATH_B9_M4: &[&str] = &[
    "4957faa551907820ed93a476704ffd826ea5502881876c87f3acefc0a8d29bce",
    "b739bc437ae5d551d144d1478ee16d1119ba15b2198a3a8b7c47976c36cb6639",
    "6f2bd73a7406c5089558c115aaae63a717e4c6947c44898e7d9600023ff15d10",
    "5cc496b84d9250622d5de1219d1f156e7973503fbd80f7f3364800bbfa2947d2",
];
const PATH_B9_M8: &[&str] =
    &["80f3f98ae8d7d9d1d2139a6a2dc94628e02fba22e125f922ea8a4c10799cb912"];
const PATH_B8_M3: &[&str] = &[
    "6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d",
    "983cb57c04cddd52634edab38a7bef85708a974f114bbd9aa9ec5d4ce6656b4b",
    "416649c1a4f116151112df7d7d3faa85d5d8c60699e153e7a3c57a1abab7a242",
];
const PATH_MIXED_M8: &[&str] = &[
    "8a3600db5c87060b03bdb7b4c7b70056808cb54e5ab927b95731d6936bff303d",
    "4290a44282949b6321f1219162bb52eceb3358250c553ee76e820bea56378f49",
];

// The exact 65-byte L65 record that sits at MIXED position 8.
const REC_L65: &[u8] =
    b"L65:\x00\xff\xfe\rabcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrst\xfe";

fn proof_json(size: u64, index: u64, root: &str, path: &[&str]) -> String {
    let mut out =
        format!("{{\"tree_size\":{size},\"leaf_index\":{index},\"root\":\"{root}\",\"audit_path\":[");
    for (i, h) in path.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        out.push('"');
        out.push_str(h);
        out.push('"');
    }
    out.push_str("]}");
    out
}

fn run(
    record: &std::path::Path,
    proof: &std::path::Path,
    size: &str,
    root: &str,
) -> std::process::Output {
    Command::new(common::bin())
        .arg("verify")
        .arg(record)
        .arg(proof)
        .arg(size)
        .arg(root)
        .output()
        .expect("failed to execute roottrace binary")
}

fn assert_verified(desc: &str, record: &[u8], proof: &[u8], size: &str, root: &str) {
    let rec = TempFile::create(record);
    let prf = TempFile::create(proof);
    let out = run(&rec.path, &prf.path, size, root);
    if out.status.code() != Some(0) || out.stdout != b"verified\n" || !out.stderr.is_empty() {
        panic!(
            "[{desc}] expected verified/exit0/empty-stderr\n\
             status: {:?}\nstdout: {:?}\nstderr: {}",
            out.status.code(),
            out.stdout,
            String::from_utf8_lossy(&out.stderr),
        );
    }
}

fn assert_verification_failed(desc: &str, record: &[u8], proof: &[u8], size: &str, root: &str) {
    let rec = TempFile::create(record);
    let prf = TempFile::create(proof);
    let out = run(&rec.path, &prf.path, size, root);
    assert_eq!(out.status.code(), Some(1), "[{desc}] must exit 1");
    assert!(out.stdout.is_empty(), "[{desc}] stdout must be empty, got {:?}", out.stdout);
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("verification failed"), "[{desc}] stderr: {err}");
}

fn assert_invalid_proof(desc: &str, proof: &[u8]) {
    let rec = TempFile::create(b"alpha");
    let prf = TempFile::create(proof);
    let out = run(&rec.path, &prf.path, "9", ROOT_B9);
    assert_eq!(out.status.code(), Some(1), "[{desc}] malformed proof must exit 1");
    assert!(out.stdout.is_empty(), "[{desc}] malformed proof must not touch stdout");
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("invalid proof"), "[{desc}] stderr: {err}");
}

// --- Success: fixed vectors --------------------------------------------------

#[test]
fn fixed_proof_vectors_verify_with_exact_record_bytes() {
    // Uneven 9-record tree at the first, the empty, the duplicate-content and
    // the last positions.
    assert_verified(
        "B9 m=0",
        b"alpha",
        proof_json(9, 0, ROOT_B9, PATH_B9_M0).as_bytes(),
        "9",
        ROOT_B9,
    );
    assert_verified(
        "B9 m=2 empty record = zero-byte record file",
        b"",
        &proof_for_index(2, ROOT_B9),
        "9",
        ROOT_B9,
    );
    assert_verified(
        "B9 m=4 (same bytes as m=0, exact position in proof)",
        b"alpha",
        proof_json(9, 4, ROOT_B9, PATH_B9_M4).as_bytes(),
        "9",
        ROOT_B9,
    );
    assert_verified(
        "B9 m=8 last record",
        b"zeta\x01tail",
        proof_json(9, 8, ROOT_B9, PATH_B9_M8).as_bytes(),
        "9",
        ROOT_B9,
    );
    // Balanced 8-record tree, full-depth path.
    assert_verified(
        "B8 m=3",
        b"gamma",
        proof_json(8, 3, ROOT_B8, PATH_B8_M3).as_bytes(),
        "8",
        ROOT_B8,
    );
    // Long binary record (NUL/CR/non-UTF-8, ends on a non-text byte) in the
    // uneven 10-record tree.
    assert_verified(
        "MIXED m=8 long binary record",
        REC_L65,
        proof_json(10, 8, ROOT_MIXED, PATH_MIXED_M8).as_bytes(),
        "10",
        ROOT_MIXED,
    );
    // One-record tree: index 0, empty path, empty record.
    assert_verified(
        "ONE_LF m=0",
        b"",
        proof_json(1, 0, ROOT_ONE_EMPTY_RECORD, &[]).as_bytes(),
        "1",
        ROOT_ONE_EMPTY_RECORD,
    );
}

/// Build a proof for B9 position `index` by actually running `prove`, so
/// positions without a hand-fixed constant are covered via real interop.
fn proof_for_index(index: u64, root: &str) -> Vec<u8> {
    let batch = TempFile::create(PAYLOAD_B9);
    let out = Command::new(common::bin())
        .arg("prove")
        .arg(&batch.path)
        .arg(index.to_string())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let line = String::from_utf8(out.stdout).unwrap();
    assert!(line.contains(&format!("\"root\":\"{root}\"")));
    line.into_bytes()
}

#[test]
fn prove_output_verifies_for_every_position_of_every_batch() {
    // Real `prove` JSON piped to `verify`; record files hold the exact record
    // bytes extracted from each payload with the same LF rule prove uses,
    // including binary and empty ones. Size/root are the independently fixed
    // constants (the role a separate confirmation channel plays in real use).
    let cases: &[(&[u8], &str, &str)] = &[
        (PAYLOAD_B9, "9", ROOT_B9),
        (PAYLOAD_B8, "8", ROOT_B8),
        (PAYLOAD_ONE_LF, "1", ROOT_ONE_EMPTY_RECORD),
        (PAYLOAD_MIXED, "10", ROOT_MIXED),
    ];

    for (batch_bytes, size, root) in cases {
        let batch = TempFile::create(batch_bytes);
        let n: u64 = size.parse().unwrap();
        for index in 0..n {
            let proved = Command::new(common::bin())
                .arg("prove")
                .arg(&batch.path)
                .arg(index.to_string())
                .output()
                .unwrap();
            assert_eq!(proved.status.code(), Some(0), "prove {index}");
            let proof_file = TempFile::create(&proved.stdout);
            let want = nth_record(batch_bytes, index);
            let record_file = TempFile::create(&want);
            let out = run(&record_file.path, &proof_file.path, size, root);
            assert_eq!(
                out.status.code(),
                Some(0),
                "verify {size}/{index}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
            assert_eq!(out.stdout, b"verified\n");
            assert!(out.stderr.is_empty());
        }
    }
}

/// LF-split a batch exactly like the documented root/prove rule, purely for
/// producing the expected record files in this test.
fn nth_file_records(data: &[u8]) -> Vec<&[u8]> {
    if data.is_empty() {
        return Vec::new();
    }
    let mut records: Vec<&[u8]> = data.split(|&b| b == b'\n').collect();
    if data.last() == Some(&b'\n') {
        records.pop();
    }
    records
}

fn nth_record(data: &[u8], index: u64) -> Vec<u8> {
    nth_file_records(data)[index as usize].to_vec()
}

#[test]
fn field_order_and_whitespace_variations_verify() {
    let compact = proof_json(9, 4, ROOT_B9, PATH_B9_M4);
    assert_verified("compact", b"alpha", compact.as_bytes(), "9", ROOT_B9);

    let pretty = format!(
        "{{\n  \"audit_path\": [\n    \"{p0}\",\n    \"{p1}\",\n    \"{p2}\",\n    \"{p3}\"\n  ],\n  \
         \"root\": \"{root}\",\n  \"leaf_index\": 4,\n  \"tree_size\": 9\n}}\n",
        p0 = PATH_B9_M4[0],
        p1 = PATH_B9_M4[1],
        p2 = PATH_B9_M4[2],
        p3 = PATH_B9_M4[3],
        root = ROOT_B9,
    );
    assert_verified("pretty + reordered", b"alpha", pretty.as_bytes(), "9", ROOT_B9);

    // Tabs/CRs and spaces around every token.
    let spaced = format!(
        "\t{{ \"tree_size\" : 9 , \"leaf_index\" : 4 , \"root\" : \"{root}\" , \
         \"audit_path\" : [ \"{p0}\" , \"{p1}\" , \"{p2}\" , \"{p3}\" ] }}\r\n",
        root = ROOT_B9,
        p0 = PATH_B9_M4[0],
        p1 = PATH_B9_M4[1],
        p2 = PATH_B9_M4[2],
        p3 = PATH_B9_M4[3],
    );
    assert_verified("whitespace everywhere", b"alpha", spaced.as_bytes(), "9", ROOT_B9);
}

// --- Record-byte fidelity ----------------------------------------------------

#[test]
fn record_file_is_used_verbatim_without_lf_splitting_or_trimming() {
    let empty_pos2 = proof_for_index(2, ROOT_B9);
    // Zero-byte record file is the empty record and verifies.
    assert_verified("zero-byte file", b"", &empty_pos2, "9", ROOT_B9);
    // Any added byte changes the record: terminating LF explicitly, plus a
    // space and CR (all preserved), all fail.
    assert_verification_failed("empty + LF", b"\n", &empty_pos2, "9", ROOT_B9);
    assert_verification_failed("empty + space", b" ", &empty_pos2, "9", ROOT_B9);
    assert_verification_failed("empty + CR", b"\r", &empty_pos2, "9", ROOT_B9);
    assert_verification_failed("empty + NUL", b"\x00", &empty_pos2, "9", ROOT_B9);

    // A normal record with an extra terminating LF must fail.
    assert_verification_failed(
        "alpha + trailing LF",
        b"alpha\n",
        proof_json(9, 0, ROOT_B9, PATH_B9_M0).as_bytes(),
        "9",
        ROOT_B9,
    );
    // Internal LF is just a byte in the record file, not a separator.
    assert_verification_failed(
        "alpha LF beta is one record file",
        b"alpha\nbeta",
        proof_json(9, 0, ROOT_B9, PATH_B9_M0).as_bytes(),
        "9",
        ROOT_B9,
    );

    // Binary record through real prove interop: NUL/non-UTF-8/CR preserved.
    let batch = TempFile::create(PAYLOAD_B9);
    let proved = Command::new(common::bin())
        .arg("prove")
        .arg(&batch.path)
        .arg("6")
        .output()
        .unwrap();
    let proof_file = TempFile::create(&proved.stdout);
    let good = TempFile::create(b"\xff\xfe\x00binary");
    let out = run(&good.path, &proof_file.path, "9", ROOT_B9);
    assert_eq!(out.status.code(), Some(0), "{}", String::from_utf8_lossy(&out.stderr));
    let bad = TempFile::create(b"\xff\xfe\x00binarX");
    let out = run(&bad.path, &proof_file.path, "9", ROOT_B9);
    assert_eq!(out.status.code(), Some(1));
    assert!(out.stdout.is_empty());
}

// --- Trusted size/root must come from the command line -----------------------

#[test]
fn proof_fields_cannot_substitute_for_trusted_values() {
    let proof = proof_json(9, 4, ROOT_B9, PATH_B9_M4);

    // Trusted size different from the proof's tree_size: fail even though the
    // proof itself is internally consistent.
    assert_verification_failed("trusted size 8 vs proof 9", b"alpha", proof.as_bytes(), "8", ROOT_B9);
    assert_verification_failed("trusted size 10 vs proof 9", b"alpha", proof.as_bytes(), "10", ROOT_B9);

    // Trusted root different from the proof's embedded root.
    let mut wrong = String::from(ROOT_B9);
    wrong.replace_range(63..64, if &ROOT_B9[63..64] == "0" { "1" } else { "0" });
    assert_verification_failed("wrong trusted root", b"alpha", proof.as_bytes(), "9", &wrong);

    // A proof embedding a different root must not verify against the trusted
    // B9 root even with matching tree_size/index/path geometry for B9.
    assert_verification_failed(
        "proof root ROOT_B8 cannot pose as B9",
        b"alpha",
        proof_json(9, 4, ROOT_B8, PATH_B9_M4).as_bytes(),
        "9",
        ROOT_B9,
    );
}

// --- Position handling and path length ---------------------------------------

#[test]
fn duplicate_content_uses_declared_position_and_path_order() {
    // "alpha" is at both 0 and 4: both proofs verify the same record bytes.
    assert_verified(
        "alpha at its m=0 proof",
        b"alpha",
        proof_json(9, 0, ROOT_B9, PATH_B9_M0).as_bytes(),
        "9",
        ROOT_B9,
    );
    assert_verified(
        "alpha at its m=4 proof",
        b"alpha",
        proof_json(9, 4, ROOT_B9, PATH_B9_M4).as_bytes(),
        "9",
        ROOT_B9,
    );
    // The m=4 path with leaf_index 0 must NOT verify: no position search.
    assert_verification_failed(
        "m=4 path mislabeled as index 0",
        b"alpha",
        proof_json(9, 0, ROOT_B9, PATH_B9_M4).as_bytes(),
        "9",
        ROOT_B9,
    );
    // Content present at m=0 but proved at a position that holds other bytes.
    assert_verification_failed(
        "alpha against the m=8 (zeta...) position",
        b"alpha",
        proof_json(9, 8, ROOT_B9, PATH_B9_M8).as_bytes(),
        "9",
        ROOT_B9,
    );
}

#[test]
fn missing_or_extra_audit_hashes_fail_including_single_record_tree() {
    // Remove one hash from the four required by B9 m=4.
    let short: Vec<&str> = PATH_B9_M4[..3].to_vec();
    assert_verification_failed(
        "path one hash short",
        b"alpha",
        proof_json(9, 4, ROOT_B9, &short).as_bytes(),
        "9",
        ROOT_B9,
    );
    // Duplicate the last hash / append an unrelated one.
    let mut long: Vec<&str> = PATH_B9_M4.to_vec();
    long.push(PATH_B9_M4[3]);
    assert_verification_failed(
        "path one hash too long",
        b"alpha",
        proof_json(9, 4, ROOT_B9, &long).as_bytes(),
        "9",
        ROOT_B9,
    );
    // Reorder two hashes: same count, wrong order.
    let mut reordered: Vec<&str> = PATH_B9_M4.to_vec();
    reordered.swap(0, 1);
    assert_verification_failed(
        "reordered path",
        b"alpha",
        proof_json(9, 4, ROOT_B9, &reordered).as_bytes(),
        "9",
        ROOT_B9,
    );
    // A one-record tree requires an empty path; a stray hash is left over.
    assert_verification_failed(
        "single record with a non-empty path",
        b"",
        proof_json(1, 0, ROOT_ONE_EMPTY_RECORD, &[PATH_B9_M8[0]]).as_bytes(),
        "1",
        ROOT_ONE_EMPTY_RECORD,
    );
    // An empty path for a multi-record tree is too short.
    assert_verification_failed(
        "9-record tree with empty path",
        b"alpha",
        proof_json(9, 0, ROOT_B9, &[]).as_bytes(),
        "9",
        ROOT_B9,
    );
}

// --- Malformed proofs --------------------------------------------------------

#[test]
fn malformed_proofs_exit_1_as_invalid_proof() {
    let h = ROOT_B9;
    let p0 = PATH_B9_M4[0];
    let p1 = PATH_B9_M4[1];
    let p2 = PATH_B9_M4[2];
    let p3 = PATH_B9_M4[3];
    let good = format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[\"{p0}\",\"{p1}\",\"{p2}\",\"{p3}\"]}}");
    assert_verified("sanity: good vector", b"alpha", good.as_bytes(), "9", ROOT_B9);

    let bad: Vec<Vec<u8>> = vec![
        b"".to_vec(),                             // empty file
        b"   ".to_vec(),                          // whitespace only
        b"null".to_vec(), b"[]".to_vec(), b"42".to_vec(),
        b"\"str\"".to_vec(), b"true".to_vec(),    // not an object
        b"{}".to_vec(),                           // object without fields
        b"{".to_vec(), b"}".to_vec(), b"{,}".to_vec(), // truncated / broken
        // Missing each required member.
        format!("{{\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"{h}\"}}").into_bytes(),
        // Duplicate members.
        format!("{{\"tree_size\":9,\"tree_size\":9,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"{h}\",\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[],\"audit_path\":[]}}").into_bytes(),
        // Wrong JSON types.
        format!("{{\"tree_size\":\"9\",\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9.0,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":-9,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4.5,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":true,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":null,\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":{{}}}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[9]}}").into_bytes(),
        // Non-canonical integer tokens.
        format!("{{\"tree_size\":09,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9e0,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":18446744073709551616,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":1e400,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        // Hash strings in the wrong shape/case.
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"{}\",\"audit_path\":[]}}", h.to_uppercase()).into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"{h}00\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"short\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[\"{}\"]}}", p0.to_uppercase()).into_bytes(),
        // Semantic range errors.
        format!("{{\"tree_size\":0,\"leaf_index\":0,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":9,\"leaf_index\":9,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        format!("{{\"tree_size\":1,\"leaf_index\":18446744073709551615,\"root\":\"{h}\",\"audit_path\":[]}}").into_bytes(),
        // Unknown member.
        format!("{{\"tree_size\":9,\"leaf_index\":4,\"root\":\"{h}\",\"audit_path\":[],\"extra\":1}}").into_bytes(),
    ];
    for case in &bad {
        assert_invalid_proof(&format!("proof {case:?}"), case);
    }

    // Trailing junk after an otherwise complete object (whitespace is fine).
    let mut trailing_ws = good.clone().into_bytes();
    trailing_ws.extend_from_slice(b"  \n\t");
    assert_verified("trailing whitespace ok", b"alpha", &trailing_ws, "9", ROOT_B9);
    let mut trailing = good.into_bytes();
    trailing.extend_from_slice(b" x");
    assert_invalid_proof("trailing data", &trailing);
}

// --- Usage and read failures -------------------------------------------------

#[test]
fn argument_errors_exit_2_with_usage_and_empty_stdout() {
    let rec = TempFile::create(b"alpha");
    let prf = TempFile::create(b"{}");
    let run_args = |args: &[&str]| {
        Command::new(common::bin())
            .arg("verify")
            .args(args)
            .output()
            .unwrap()
    };
    let r = rec.path.to_str().unwrap();
    let p = prf.path.to_str().unwrap();

    for args in [
        vec![r, p, "9"],                       // one missing
        vec![r, p],                            // two missing
        vec![r],                               // only the record path
        vec![],                                // nothing
        vec![r, p, "9", ROOT_B9, "extra"],     // one too many
    ] {
        let out = run_args(&args);
        assert_eq!(out.status.code(), Some(2), "args {args:?}");
        assert!(out.stdout.is_empty(), "args {args:?}");
        assert!(
            String::from_utf8_lossy(&out.stderr).contains("Usage"),
            "args {args:?}: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }

    // The trusted size must be an ASCII decimal POSITIVE integer <= u64::MAX.
    for bad_size in ["0", "00", "-1", "+9", "9.0", " 9", "9 ", "0x9", "abc", "", "18446744073709551616"] {
        let out = Command::new(common::bin())
            .arg("verify")
            .arg(r)
            .arg(p)
            .arg(bad_size)
            .arg(ROOT_B9)
            .output()
            .unwrap();
        assert_eq!(out.status.code(), Some(2), "size {bad_size:?}");
        assert!(out.stdout.is_empty());
        let err = String::from_utf8_lossy(&out.stderr);
        assert!(err.contains("Usage") && err.contains("trusted tree size"), "size {bad_size:?}: {err}");
    }

    // The trusted root must be exactly 64 lowercase hex characters.
    for bad_root in [
        "",
        "abc",
        &ROOT_B9[..63],
        &format!("{ROOT_B9}a"),
        &ROOT_B9.to_uppercase(),
        &format!("{ROOT_B9} "),
        "z".repeat(64).as_str(),
    ] {
        let out = Command::new(common::bin())
            .arg("verify")
            .arg(r)
            .arg(p)
            .arg("9")
            .arg(bad_root)
            .output()
            .unwrap();
        assert_eq!(out.status.code(), Some(2), "root {bad_root:?}");
        assert!(out.stdout.is_empty());
        let err = String::from_utf8_lossy(&out.stderr);
        assert!(err.contains("Usage") && err.contains("trusted root"), "root {bad_root:?}: {err}");
    }
}

#[test]
fn read_failures_exit_1_with_empty_stdout() {
    let proof = proof_json(9, 0, ROOT_B9, PATH_B9_M0);
    let prf = TempFile::create(proof.as_bytes());
    let rec = TempFile::create(b"alpha");

    // Missing record file and record path pointing at a directory.
    let missing_rec = TempFile::create(b"x");
    let missing_rec_path = missing_rec.path.clone();
    drop(missing_rec);
    let out = run(&missing_rec_path, &prf.path, "9", ROOT_B9);
    assert_eq!(out.status.code(), Some(1));
    assert!(out.stdout.is_empty());
    assert!(!out.stderr.is_empty());

    let dir = TempDir::create();
    let out = run(&dir.path, &prf.path, "9", ROOT_B9);
    assert_eq!(out.status.code(), Some(1));
    assert!(out.stdout.is_empty());
    assert!(!out.stderr.is_empty());

    // Missing proof file and proof path pointing at a directory.
    let missing_prf = TempFile::create(b"x");
    let missing_prf_path = missing_prf.path.clone();
    drop(missing_prf);
    let out = run(&rec.path, &missing_prf_path, "9", ROOT_B9);
    assert_eq!(out.status.code(), Some(1));
    assert!(out.stdout.is_empty());
    assert!(!out.stderr.is_empty());

    let dir = TempDir::create();
    let out = run(&rec.path, &dir.path, "9", ROOT_B9);
    assert_eq!(out.status.code(), Some(1));
    assert!(out.stdout.is_empty());
    assert!(!out.stderr.is_empty());
}

#[test]
fn version_root_prove_behavior_is_unchanged() {
    let out = Command::new(common::bin()).arg("--version").output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    assert!(out.stderr.is_empty());
    assert_eq!(out.stdout, b"roottrace 0.1.0\n");

    let batch = TempFile::create(PAYLOAD_B9);
    let out = Command::new(common::bin())
        .arg("root")
        .arg(&batch.path)
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    assert_eq!(&out.stdout[..64], ROOT_B9.as_bytes());

    let out = Command::new(common::bin())
        .arg("prove")
        .arg(&batch.path)
        .arg("0")
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let proved = String::from_utf8(out.stdout).unwrap();
    assert!(proved.contains(&format!("\"root\":\"{ROOT_B9}\"")));
}
