//! End-to-end regression tests for `roottrace verify` on trees whose size
//! sits at the unsigned 64-bit boundary: 2^63 (9223372036854775808, a
//! power-of-two tree), 2^63+1 (9223372036854775809, uneven) and 2^64-1
//! (18446744073709551615, uneven). Such batches can never be materialised,
//! so the proofs are synthetic: one fixed target record and an audit path
//! whose element i is the 64-character lowercase hex of i. The trusted roots
//! are fixed constants generated by `tests/reference/rfc6962_vectors.py`,
//! which recombines (record, leaf_index, tree_size, audit_path) with two
//! structurally different, hashlib-based RFC 6962 verifiers that must agree;
//! they are never derived from roottrace output.
//!
//! Coverage:
//!   * valid proofs verify at the first/last record and on both sides of the
//!     left/right subtree boundary, including leaf indices past the 32-bit
//!     range: stdout is exactly "verified\n", exit 0, stderr empty
//!   * tree sizes and indices keep their exact 64-bit integer meaning: the
//!     high bit set is neither truncated, negated nor treated as a smaller
//!     batch (off-by-one trusted sizes and off-by-one leaf indices fail)
//!   * uneven trees keep the RFC geometry: the last record of a 2^63+1 tree
//!     has a one-hash path (no duplicated tail record, no padding)
//!   * a path with one hash missing, one hash extra, or one hash altered
//!     fails verification (exit 1, empty stdout, "verification failed" on
//!     stderr) — never a usage error or an abnormal termination
//!   * the trusted tree size comes only from the command line: with record
//!     and path unchanged, any other legal trusted size fails even though
//!     the proof carries its own self-consistent tree_size
//!   * for the maximum tree size, leaf_index == tree_size is an INVALID
//!     PROOF (exit 1, "invalid proof"), kept distinct from a cryptographic
//!     verification failure

mod common;

use std::process::Command;

use common::TempFile;

/// The fixed target record of every big-tree case (NUL and non-UTF-8 bytes
/// included, so record-byte fidelity stays exercised).
const BIG_TREE_RECORD: &[u8] = b"big-tree-record\x00\xff\xfe";

struct BigCase {
    size: u64,
    index: u64,
    depth: usize,
    root: &'static str,
}

// Generated by tests/reference/rfc6962_vectors.py (two independent root
// computations agree on every case).
const BIG_TREE_CASES: &[BigCase] = &[
    // 2**63 (power-of-two tree), first record; audit_path depth 63
    BigCase { size: 9223372036854775808, index: 0, depth: 63, root: "ee3d1ca8d1cb646feeaa90be0fb22c6d8674b545ab84e113a3fe41af630838dc" },
    // 2**63, record 2**32-1 (top of 32-bit range); audit_path depth 63
    BigCase { size: 9223372036854775808, index: 4294967295, depth: 63, root: "92898a452dc9806a49b20c0f1387e3f595275a532f9384e6982ea1d5c1433770" },
    // 2**63, record 2**32 (first index past 32 bits); audit_path depth 63
    BigCase { size: 9223372036854775808, index: 4294967296, depth: 63, root: "afcfe7edcae41e08965824b245fd42bd162c459feecedd1bf581349b664d8ebe" },
    // 2**63, record k-1 (last of left subtree); audit_path depth 63
    BigCase { size: 9223372036854775808, index: 4611686018427387903, depth: 63, root: "b17f9560c7184c222ad3f7f0cb7634285c0eebf1e197a50953714c4af1a32404" },
    // 2**63, record k (first of right subtree); audit_path depth 63
    BigCase { size: 9223372036854775808, index: 4611686018427387904, depth: 63, root: "a386e67cd2e721b651aadb134199e3f32ac3f3181e27b2305917ae8a1bf296a2" },
    // 2**63, last record; audit_path depth 63
    BigCase { size: 9223372036854775808, index: 9223372036854775807, depth: 63, root: "c035bef423e3cc7dcaa0a23687221787e739ef1ad6717b6c9e562addde480fc6" },
    // 2**63+1 (uneven), first record; audit_path depth 64
    BigCase { size: 9223372036854775809, index: 0, depth: 64, root: "00374def40979015a9865a6e90b2fbd6effc8e235befab92877dcdf5e63f0361" },
    // 2**63+1 (uneven), record k-1 (last of left subtree); audit_path depth 64
    BigCase { size: 9223372036854775809, index: 9223372036854775807, depth: 64, root: "b44d5ad09c3f5dbfb1e67033863f8a6253d79f5b12ec2f3a591c6289d4da40e1" },
    // 2**63+1 (uneven), last record = k (lone right subtree); audit_path depth 1
    BigCase { size: 9223372036854775809, index: 9223372036854775808, depth: 1, root: "e3004442ff263eaa1f454e07a87f17253cb9aadc06d4e2df78e23db1b3f82fd3" },
    // 2**64-1 (uneven), first record; audit_path depth 64
    BigCase { size: 18446744073709551615, index: 0, depth: 64, root: "00374def40979015a9865a6e90b2fbd6effc8e235befab92877dcdf5e63f0361" },
    // 2**64-1 (uneven), record k-1 (last of left subtree); audit_path depth 64
    BigCase { size: 18446744073709551615, index: 9223372036854775807, depth: 64, root: "b44d5ad09c3f5dbfb1e67033863f8a6253d79f5b12ec2f3a591c6289d4da40e1" },
    // 2**64-1 (uneven), record k (first of right subtree); audit_path depth 64
    BigCase { size: 18446744073709551615, index: 9223372036854775808, depth: 64, root: "0173223adb9663b2cf479e79b5a9e8533ca58a72128e06b3e784a4b34df5f0bb" },
    // 2**64-1 (uneven), last record; audit_path depth 63
    BigCase { size: 18446744073709551615, index: 18446744073709551614, depth: 63, root: "c035bef423e3cc7dcaa0a23687221787e739ef1ad6717b6c9e562addde480fc6" },
];

const SIZE_POW63: u64 = 9223372036854775808;
const SIZE_POW63_PLUS1: u64 = 9223372036854775809;
const SIZE_MAX: u64 = 18446744073709551615;

/// The synthetic audit path shared with the reference generator: element i
/// is the 64-character lowercase hex of i.
fn audit_path(depth: usize) -> Vec<String> {
    (0..depth).map(|i| format!("{i:064x}")).collect()
}

fn proof_json(size: u64, index: u64, root: &str, path: &[String]) -> String {
    let mut out =
        format!("{{\"tree_size\":{size},\"leaf_index\":{index},\"root\":\"{root}\",\"audit_path\":[");
    for (i, h) in path.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        out.push('"');
        out.push_str(h);
        out.push('"');
    }
    out.push_str("]}");
    out
}

fn run(record: &std::path::Path, proof: &std::path::Path, size: &str, root: &str) -> std::process::Output {
    Command::new(common::bin())
        .arg("verify")
        .arg(record)
        .arg(proof)
        .arg(size)
        .arg(root)
        .output()
        .expect("failed to execute roottrace binary")
}

/// The documented success path, checked strictly: exit status 0, stdout
/// exactly "verified\n", stderr empty.
fn assert_verified(desc: &str, record: &[u8], proof: &[u8], size: &str, root: &str) {
    let rec = TempFile::create(record);
    let prf = TempFile::create(proof);
    let out = run(&rec.path, &prf.path, size, root);
    if out.status.code() != Some(0) || out.stdout != b"verified\n" || !out.stderr.is_empty() {
        panic!(
            "[{desc}] expected verified/exit0/empty-stderr\n\
             status: {:?}\nstdout: {:?}\nstderr: {}",
            out.status.code(),
            out.stdout,
            String::from_utf8_lossy(&out.stderr),
        );
    }
}

/// A cryptographic mismatch: exit status 1 (not a usage error, not a
/// crash), stdout empty, stderr reporting the verification failure.
fn assert_verification_failed(desc: &str, record: &[u8], proof: &[u8], size: &str, root: &str) {
    let rec = TempFile::create(record);
    let prf = TempFile::create(proof);
    let out = run(&rec.path, &prf.path, size, root);
    assert_eq!(out.status.code(), Some(1), "[{desc}] must exit 1");
    assert!(out.stdout.is_empty(), "[{desc}] stdout must be empty, got {:?}", out.stdout);
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("verification failed"), "[{desc}] stderr: {err}");
}

/// A malformed proof: exit status 1, stdout empty, stderr reporting the
/// format problem — and NOT phrased as a cryptographic verification
/// failure, so the two stay distinguishable.
fn assert_invalid_proof(desc: &str, record: &[u8], proof: &[u8], size: &str, root: &str) {
    let rec = TempFile::create(record);
    let prf = TempFile::create(proof);
    let out = run(&rec.path, &prf.path, size, root);
    assert_eq!(out.status.code(), Some(1), "[{desc}] malformed proof must exit 1");
    assert!(out.stdout.is_empty(), "[{desc}] malformed proof must not touch stdout");
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("invalid proof"), "[{desc}] stderr: {err}");
    assert!(
        !err.contains("verification failed"),
        "[{desc}] a format problem must not be reported as a verification failure: {err}"
    );
}

fn case_proof(case: &BigCase) -> String {
    proof_json(case.size, case.index, case.root, &audit_path(case.depth))
}

// --- Success: first/last records and both sides of the subtree boundary ----

#[test]
fn big_tree_proofs_verify_at_boundary_positions() {
    for case in BIG_TREE_CASES {
        let desc = format!(
            "tree_size={} leaf_index={} (depth {})",
            case.size, case.index, case.depth
        );
        let proof = case_proof(case);
        // The proof and the command line must carry the exact decimal
        // spelling of the full-width values (no float, no truncation).
        assert!(proof.contains(&format!("\"tree_size\":{}", case.size)), "{desc}");
        assert!(proof.contains(&format!("\"leaf_index\":{}", case.index)), "{desc}");
        assert_verified(&desc, BIG_TREE_RECORD, proof.as_bytes(), &case.size.to_string(), case.root);
    }
}

#[test]
fn big_tree_uneven_last_record_uses_single_hash_path_not_padding() {
    // The last record of a 2^63+1 tree is the lone leaf of the right
    // subtree: its path is exactly MTH of the left 2^63 records — ONE hash.
    // A scheme that pads to a power of two (duplicating the tail record or
    // appending empty records) would demand a 64-hash path instead.
    let case = BIG_TREE_CASES
        .iter()
        .find(|c| c.size == SIZE_POW63_PLUS1 && c.index == SIZE_POW63)
        .expect("the 2^63+1 last-record case");
    assert_eq!(case.depth, 1, "reference geometry: lone right subtree, one sibling hash");
    let proof = case_proof(case);
    assert!(proof.contains("\"audit_path\":[\"0000000000000000000000000000000000000000000000000000000000000000\"]"));
    assert_verified(
        "2^63+1 last record, one-hash path",
        BIG_TREE_RECORD,
        proof.as_bytes(),
        &case.size.to_string(),
        case.root,
    );
}

// --- Exact 64-bit meaning of tree size and leaf index ----------------------

#[test]
fn big_tree_trusted_size_is_exact_and_never_taken_from_the_proof() {
    for case in BIG_TREE_CASES {
        let proof = case_proof(case);
        // Record, path and proof are unchanged; only the trusted size moves
        // to another legal value. The proof's own tree_size must not
        // substitute for the trusted one, however self-consistent it is.
        let mut variants = vec![case.size - 1, 9];
        if case.size < SIZE_MAX {
            variants.push(case.size + 1);
        }
        for other in variants {
            assert_verification_failed(
                &format!(
                    "trusted size {other} vs proof tree_size {} (leaf_index {})",
                    case.size, case.index
                ),
                BIG_TREE_RECORD,
                proof.as_bytes(),
                &other.to_string(),
                case.root,
            );
        }
    }
}

#[test]
fn big_tree_leaf_index_participates_exactly_beyond_32_bits() {
    // Same record, same path, same root, same tree size — only the claimed
    // position moves by one. The recombination geometry changes, so the
    // proof must fail; an index truncated to 32 bits (or to the signed
    // range) would conflate these positions.
    let case = BIG_TREE_CASES
        .iter()
        .find(|c| c.size == SIZE_POW63 && c.index == 4294967296)
        .expect("the 2^32 index case");
    for off_by_one in [case.index - 1, case.index + 1] {
        let proof = proof_json(case.size, off_by_one, case.root, &audit_path(case.depth));
        assert_verification_failed(
            &format!("leaf_index {off_by_one} reusing the proof for {}", case.index),
            BIG_TREE_RECORD,
            proof.as_bytes(),
            &case.size.to_string(),
            case.root,
        );
    }
    // The 2^32-1 / 2^32 pair must not be conflated either: the proof for
    // one must fail at the other.
    let below = BIG_TREE_CASES
        .iter()
        .find(|c| c.size == SIZE_POW63 && c.index == 4294967295)
        .expect("the 2^32-1 index case");
    let proof = proof_json(case.size, below.index, case.root, &audit_path(case.depth));
    assert_verification_failed(
        "leaf_index 2^32-1 with the 2^32 proof",
        BIG_TREE_RECORD,
        proof.as_bytes(),
        &case.size.to_string(),
        case.root,
    );
}

#[test]
fn big_tree_trusted_root_mismatch_fails() {
    for case in BIG_TREE_CASES {
        let mut wrong = case.root.to_string();
        let last = wrong.len() - 1;
        let replacement = if wrong.ends_with('0') { "1" } else { "0" };
        wrong.replace_range(last.., replacement);
        let proof = case_proof(case);
        assert_verification_failed(
            &format!("trusted root one hex digit off (size {}, index {})", case.size, case.index),
            BIG_TREE_RECORD,
            proof.as_bytes(),
            &case.size.to_string(),
            &wrong,
        );
    }
}

// --- Path integrity: missing, extra or altered hashes ----------------------

#[test]
fn big_tree_path_missing_extra_or_altered_hash_fails() {
    for case in BIG_TREE_CASES {
        let path = audit_path(case.depth);
        let desc = format!("tree_size={} leaf_index={}", case.size, case.index);

        // One hash short (for the depth-1 case this is the empty path).
        let short = &path[..path.len() - 1];
        assert_verification_failed(
            &format!("{desc}: path one hash short"),
            BIG_TREE_RECORD,
            proof_json(case.size, case.index, case.root, short).as_bytes(),
            &case.size.to_string(),
            case.root,
        );

        // One hash too many.
        let mut long = path.clone();
        long.push(format!("{:064x}", case.depth));
        assert_verification_failed(
            &format!("{desc}: path one hash too long"),
            BIG_TREE_RECORD,
            proof_json(case.size, case.index, case.root, &long).as_bytes(),
            &case.size.to_string(),
            case.root,
        );

        // One hash altered in content (same length, same count).
        let mut altered = path.clone();
        let mid = altered.len() / 2;
        let first = altered[mid].remove(0);
        let replacement = if first == '0' { '1' } else { '0' };
        altered[mid].insert(0, replacement);
        assert_verification_failed(
            &format!("{desc}: path hash {mid} altered"),
            BIG_TREE_RECORD,
            proof_json(case.size, case.index, case.root, &altered).as_bytes(),
            &case.size.to_string(),
            case.root,
        );
    }
}

// --- Record bytes stay verbatim --------------------------------------------

#[test]
fn big_tree_record_bytes_are_verbatim() {
    let case = &BIG_TREE_CASES[0];
    let proof = case_proof(case);
    let size = case.size.to_string();

    // One content byte changed.
    let mut tampered = BIG_TREE_RECORD.to_vec();
    *tampered.last_mut().unwrap() ^= 0x01;
    assert_verification_failed(
        "record with last byte flipped",
        &tampered,
        proof.as_bytes(),
        &size,
        case.root,
    );
    // A trailing LF/space/NUL appended to the record changes it.
    for suffix in [b"\n".as_slice(), b" ", b"\x00"] {
        let mut longer = BIG_TREE_RECORD.to_vec();
        longer.extend_from_slice(suffix);
        assert_verification_failed(
            &format!("record + trailing {suffix:?}"),
            &longer,
            proof.as_bytes(),
            &size,
            case.root,
        );
    }
}

// --- leaf_index == tree_size at the maximum size is a format error ---------

#[test]
fn max_tree_size_index_equal_to_size_is_invalid_proof_not_a_verification_failure() {
    // Take the VALID maximum-size proof (last record of a 2^64-1 tree) and
    // bump only the position to leaf_index == tree_size: the position does
    // not exist, so this is a proof-format error, distinct from a
    // cryptographic mismatch at a legal position.
    let valid_last = BIG_TREE_CASES
        .iter()
        .find(|c| c.size == SIZE_MAX && c.index == SIZE_MAX - 1)
        .expect("the maximum-size last-record case");
    let proof = proof_json(SIZE_MAX, SIZE_MAX, valid_last.root, &audit_path(valid_last.depth));
    assert_invalid_proof(
        "leaf_index == tree_size == 2^64-1",
        BIG_TREE_RECORD,
        proof.as_bytes(),
        &SIZE_MAX.to_string(),
        valid_last.root,
    );

    // Same boundary one size down: leaf_index == 2^63 in a 2^63 tree.
    let proof = proof_json(SIZE_POW63, SIZE_POW63, valid_last.root, &audit_path(valid_last.depth));
    assert_invalid_proof(
        "leaf_index == tree_size == 2^63",
        BIG_TREE_RECORD,
        proof.as_bytes(),
        &SIZE_POW63.to_string(),
        valid_last.root,
    );

    // Sanity: the legal maximum position itself verifies (covered above,
    // restated here to pin the boundary from the invalid side).
    let proof = case_proof(valid_last);
    assert_verified(
        "leaf_index == 2^64-2 is legal",
        BIG_TREE_RECORD,
        proof.as_bytes(),
        &SIZE_MAX.to_string(),
        valid_last.root,
    );
}
